// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.apple.apps",
  name: "NullTrace",
  homepage: "https://apps.apple.com/us/app/nulltrace/id6758411859",
  image_id: "ed496369-cf02-4c99-f57a-27cd5d617200",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/audiozone/id6758411859",
    android: "",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "",
    universal: "https://nulltrace.app",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
