// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.ripio.android&hl=en&gl=US",
    browser: null,
    chrome:
      "https://chrome.google.com/webstore/detail/ripio-portal/ddamhapapianibkkkcclabgicmpnpdnj",
    edge: "https://chrome.google.com/webstore/detail/ripio-portal/ddamhapapianibkkkcclabgicmpnpdnj",
    firefox: null,
    ios: "https://apps.apple.com/ar/app/ripio-comprar-bitcoin-y-eth/id1221006761",
    linux: null,
    mac: "",
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://ripio.com/portal",
  id: "com.ripio",
  image_id: "fd56c695-ce58-4df5-1625-767571c80700",
  mobile: {
    native: "ripio://portal",
    universal: null,
  },
  name: "Ripio Portal",
  rdns: null,
} as const;
