// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "org.onyx",
  name: "Onyx Wallet",
  homepage: "https://onyx.org",
  image_id: "f9d19561-adb3-4526-b852-77ba3d534400",
  app: {
    browser: null,
    ios: "https://apps.apple.com/in/app/onyx-xcn-wallet/id6748654539",
    android:
      "https://play.google.com/store/apps/details?id=com.onyx.walletprod&pcampaignid=web_share",
    mac: null,
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "onyxwallet:///",
    universal: "https://wallet.onyx.org",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
