// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.onlybulls",
  name: "OnlyBulls Wallet",
  homepage: "https://onlybulls.com",
  image_id: "f51e7b10-7a66-437f-8d13-666c660e8500",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/onlybulls/id6746166943",
    android:
      "https://play.google.com/store/apps/details?id=com.askroi.onlybulls",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "",
    universal: "https://onlybulls.com",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
