// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "io.cosmostation",
  name: "Cosmostation",
  homepage: "https://www.cosmostation.io/",
  image_id: "ea26c3c8-adb6-4dc4-ee02-35d6eee02800",
  app: {
    browser: null,
    ios: "https://apps.apple.com/kr/app/cosmostation/id1459830339",
    android:
      "https://play.google.com/store/apps/details?id=wannabit.io.cosmostaion",
    mac: null,
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "cosmostation://",
    universal: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
