// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.walletconnect.com",
  name: "SampleW",
  homepage: "https://walletconnect.com",
  image_id: "361c7dfd-e4a1-46ce-e42a-241443ed5700",
  app: {
    browser: null,
    ios: null,
    android: null,
    mac: null,
    windows: null,
    linux: null,
    chrome: "https://cloud.walletconnect.com",
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: "com.walletconnect.com",
  mobile: {
    native: null,
    universal: null,
  },
  desktop: {
    native: "sampleW://",
    universal: "https://wallet-connect.sampleW.com",
  },
} as const;
