// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "network.blackfort",
  name: "BlackFort Wallet",
  homepage: "https://blackfort.network",
  image_id: "f2cf0909-3e1e-4f67-8c3f-2b69f7a5eb00",
  app: {
    browser: null,
    ios: "https://apps.apple.com/pl/app/blackfort-wallet/id6447954137",
    android:
      "https://play.google.com/store/apps/details?id=exchange.blackfort.blackfortwallet&hl=en_US",
    mac: null,
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "blackfortwc://",
    universal: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
