// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.qubetics",
  name: "QubeticsWallet",
  homepage: "https://www.qubetics.com/",
  image_id: "f6afe67c-41e9-44fc-075a-3e7eda291000",
  app: {
    browser: "",
    ios: "https://apps.apple.com/in/app/qubetics-wallet/id6746333540",
    android:
      "https://play.google.com/store/apps/details?id=com.qubetics.wallet",
    mac: "",
    windows: "",
    linux: "",
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "qubetics://",
    universal: "",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
