/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DropStorage, DropStorageInterface } from "../DropStorage";

const _abi = [
  {
    type: "function",
    name: "DROP_STORAGE_POSITION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
];

const _bytecode =
  "0x61010361003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80637cc37151146038575b600080fd5b603e6050565b60405190815260200160405180910390f35b60ff19607c60017fbc63558797adc09ce5b77f3ca89acfccabdd075e03de61144467402677b956b260a7565b604051602001608d91815260200190565b604051602081830303815290604052805190602001201681565b8181038181111560c757634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220a4dce1aab5f812c271fb37591e8c4d927afa7053a65da3f1c701b00366b9449164736f6c63430008170033";

type DropStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DropStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DropStorage__factory extends ContractFactory {
  constructor(...args: DropStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DropStorage> {
    return super.deploy(overrides || {}) as Promise<DropStorage>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DropStorage {
    return super.attach(address) as DropStorage;
  }
  override connect(signer: Signer): DropStorage__factory {
    return super.connect(signer) as DropStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DropStorageInterface {
    return new utils.Interface(_abi) as DropStorageInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DropStorage {
    return new Contract(address, _abi, signerOrProvider) as DropStorage;
  }
}
