/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IERC721Supply, IERC721SupplyInterface } from "../IERC721Supply";

const _abi = [
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
];

export class IERC721Supply__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721SupplyInterface {
    return new utils.Interface(_abi) as IERC721SupplyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721Supply {
    return new Contract(address, _abi, signerOrProvider) as IERC721Supply;
  }
}
