/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRoyaltyPayments,
  IRoyaltyPaymentsInterface,
} from "../IRoyaltyPayments";

const _abi = [
  {
    type: "function",
    name: "getRoyalty",
    inputs: [
      {
        name: "tokenAddress",
        type: "address",
        internalType: "address",
      },
      {
        name: "tokenId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "value",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "recipients",
        type: "address[]",
        internalType: "address payable[]",
      },
      {
        name: "amounts",
        type: "uint256[]",
        internalType: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setRoyaltyEngine",
    inputs: [
      {
        name: "_royaltyEngineAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [
      {
        name: "interfaceId",
        type: "bytes4",
        internalType: "bytes4",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "RoyaltyEngineUpdated",
    inputs: [
      {
        name: "previousAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newAddress",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
];

export class IRoyaltyPayments__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltyPaymentsInterface {
    return new utils.Interface(_abi) as IRoyaltyPaymentsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRoyaltyPayments {
    return new Contract(address, _abi, signerOrProvider) as IRoyaltyPayments;
  }
}
