// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "link.app.wwallet",
  name: "Wirex Wallet",
  homepage: "https://wwallet.app.link/W1YKPgySZsb",
  image_id: "769739aa-ff45-4db5-c6e6-70590741ec00",
  app: {
    browser: "https://wirexapp.com/wirex-wallet",
    ios: "https://apps.apple.com/app/wirex-wallet-crypto-and-defi/id1594165139",
    android: "https://play.google.com/store/apps/details?id=com.wirex.wallet",
    mac: "",
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "wirexwallet://",
    universal:
      "https://wwallet.app.link/wc?uri=wc:00e46b69-d0cc-4b3e-b6a2-cee442f97188@1?bridge=https%3A%2F%2Fbridge.walletconnect.org&key=91303dedf64285cbbaf9120f6e9d160a5c8aa3deb67017a3874cd272323f48ae",
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
