// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.unstoppabledomains.manager",
    browser: "https://unstoppabledomains.com/",
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/unstoppable-domains/id1544748602",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: "https://unstoppabledomains.com/",
  },
  homepage: "https://unstoppabledomains.com/",
  id: "com.unstoppabledomains",
  image_id: "4725dda0-4471-4d0f-7adf-6bbe8b929c00",
  mobile: {
    native: "unstoppabledomains://",
    universal: "https://unstoppabledomains.com/mobile",
  },
  name: "Unstoppable Domains",
  rdns: null,
} as const;
