// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "app.pluswallet",
  name: "Plus Wallet",
  homepage: "https://pluswallet.app",
  image_id: "2c21491b-58ce-47bb-ace9-bdef71f43600",
  app: {
    browser: null,
    ios: "https://apps.apple.com/us/app/plus-wallet-app/id6467651848",
    android: "https://play.google.com/store/apps/details?id=com.PlusWallet",
    mac: null,
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "pluswallet://",
    universal: "https://pluswallet.app",
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
