// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.bifrostwallet",
  name: "Bifrost Wallet",
  homepage: "https://bifrostwallet.com",
  image_id: "c1ab3987-7e3c-43fa-0b27-c746f6135a00",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/bifrost-wallet/id1577198351",
    android:
      "https://play.google.com/store/apps/details?id=com.bifrostwallet.app",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "com.bifrostwallet",
  mobile: {
    native: "bifrostwallet://",
    universal: "https://app.bifrostwallet.com/",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
