export {
  AUTH_TOKEN_LOCAL_STORAGE_NAME,
  AuthProvider,
  DEVICE_SHARE_LOCAL_STORAGE_NAME,
  DEVICE_SHARE_LOCAL_STORAGE_NAME_DEPRECATED,
  EmbeddedWalletSdk,
  RecoveryShareManagement,
  UserWalletStatus,
  WALLET_USER_DETAILS_LOCAL_STORAGE_NAME,
  WALLET_USER_ID_LOCAL_STORAGE_NAME,
  type AuthAndWalletRpcReturnType,
  type AuthDetails,
  type AuthLoginReturnType,
  type AuthStoredTokenWithCookieReturnType,
  type EmbeddedWalletConstructorType,
  type GetAddressReturnType,
  type GetAuthDetailsReturnType,
  type GetHeadlessLoginLinkReturnType,
  type GetUser,
  type GetUserWalletStatusRpcReturnType,
  type InitializedUser,
  type LogoutReturnType,
  type SendEmailOtpReturnType,
  type SetUpWalletRpcReturnType,
  type SignMessageReturnType,
  type SignTransactionReturnType,
  type SignedTypedDataReturnType,
  type StoredTokenType,
} from "../../../wallets/embedded/implementations/index.js";
