// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.travisheron.swopapp&pli=1",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/swop-connecting-the-world/id1593201322",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://swopme.co/",
  id: "co.swopme",
  image_id: "6e773b07-efcc-40eb-b3a2-300efc5df800",
  mobile: {
    native: "swopapp://",
    universal: "https://swopme.app",
  },
  name: "SWOP",
  rdns: null,
} as const;
