// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.frostfirewallet",
  name: "Frostfire",
  homepage: "https://frostfirewallet.com",
  image_id: "3611cc5f-4da4-49ca-dcce-f3bd39cee600",
  app: {
    browser: "",
    ios: "",
    android:
      "https://play.google.com/store/apps/details?id=com.velas.frostfire",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "frostfire://wc",
    universal: "",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
