// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "org.talkapp",
  name: "Talk+",
  homepage: "https://www.talkapp.org/",
  image_id: "d24cdd56-6f55-42da-631b-c25974c36f00",
  app: {
    browser: "https://www.talkapp.org/",
    ios: "https://apps.apple.com/hk/app/talk-send-crypto-with-friends/id1547227377?l=en",
    android:
      "https://play.google.com/store/apps/details?id=org.talkapp&hl=en&gl=US",
    mac: null,
    windows: null,
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "talkapp://",
    universal: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
