// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.reown",
  name: "React Native Sample Wallet",
  homepage: "https://reown.com/walletkit",
  image_id: "51331664-fae8-45d5-77d6-b550028b0200",
  app: {
    browser: "",
    ios: "https://testflight.apple.com/join/kdlGVGLo",
    android: "https://appdistribution.firebase.dev/i/e7711e780547234e",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "rn-web3wallet-internal://",
    universal: "https://appkit-lab.reown.com/rn_walletkit_internal",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
