// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.nufinetes",
  name: "Nufinetes",
  homepage: "https://www.nufinetes.com",
  image_id: "4bb6c1ca-4196-4ba3-ece2-c3d335e1f800",
  app: {
    browser: "https://www.nufinetes.com",
    ios: "https://apps.apple.com/us/app/nufinetes/id1609562349",
    android:
      "https://play.google.com/store/apps/details?id=com.vimworld.wallet",
    mac: "https://apps.apple.com/us/app/nufinetes-desktop/id1629768725",
    windows:
      "https://d3va9f6jgm4z2y.cloudfront.net/nufinetes-prod/Nufinetes_Windows_latest.exe",
    linux: null,
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "vimwallet://",
    universal: "https://apple.vimworld.org",
  },
  desktop: {
    native: "vimwallet://",
    universal: null,
  },
} as const;
