/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface ReentrancyGuardStorageInterface extends utils.Interface {
  functions: {
    "REENTRANCY_GUARD_STORAGE_POSITION()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "REENTRANCY_GUARD_STORAGE_POSITION"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "REENTRANCY_GUARD_STORAGE_POSITION",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "REENTRANCY_GUARD_STORAGE_POSITION",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ReentrancyGuardStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrancyGuardStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    REENTRANCY_GUARD_STORAGE_POSITION(
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  REENTRANCY_GUARD_STORAGE_POSITION(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    REENTRANCY_GUARD_STORAGE_POSITION(
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    REENTRANCY_GUARD_STORAGE_POSITION(
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    REENTRANCY_GUARD_STORAGE_POSITION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
