// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "io.mywallet",
  name: "My Wallet",
  homepage: "https://mywallet.io/?utm_source=wc",
  image_id: "3db0c04f-9792-4628-044e-865878119200",
  app: {
    browser: "",
    ios: "https://get.mywallet.io/ios-store?utm_source=wc",
    android: "https://get.mywallet.io/android-store?utm_source=wc",
    mac: "https://get.mytonwallet.io/",
    windows: "https://get.mytonwallet.io/",
    linux: "https://get.mytonwallet.io/",
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "mywallet-wc://",
    universal: "https://my.tt/wc/",
  },
  desktop: {
    native: "mywallet-wc://",
    universal: "",
  },
} as const;
