// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.moneda",
  name: "Moneda",
  homepage: "https://moneda.com",
  image_id: "4dba78bc-25b5-4deb-6215-7838aae16f00",
  app: {
    browser: "",
    ios: "https://apps.apple.com/app/moneda/id6741869236",
    android: "https://play.google.com/store/apps/details?id=com.moneda.io",
    mac: "",
    windows: "",
    linux: "",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "",
    universal: "https://auth.moneda.com",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
