// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=io.moonstake.wallet&hl=en",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/moonstake-wallet/id1502532651",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://moonstake.io",
  id: "io.moonstake",
  image_id: "22374fae-244c-4224-2e3d-c14912f98a00",
  mobile: {
    native: "moonstake://",
    universal: "https://moonstake.io/launchApp",
  },
  name: "MOONSTAKE",
  rdns: null,
} as const;
