// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "fi.nu",
  name: "NuFi",
  homepage: "https://nu.fi",
  image_id: "65e07e9f-183a-4f6c-6ca5-4964eda1ef00",
  app: {
    browser: "https://wallet.nu.fi/wallet_connect/connector/redirect",
    ios: null,
    android: null,
    mac: null,
    windows: null,
    linux: null,
    chrome:
      "https://chrome.google.com/webstore/detail/nufi/gpnihlnnodeiiaakbikldcihojploeca",
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: null,
    universal: null,
  },
  desktop: {
    native: null,
    universal: "https://wallet.nu.fi/wallet_connect/connector/redirect",
  },
} as const;
