// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "utila.io",
  name: "Utila",
  homepage: "https://utila.io/",
  image_id: "0838406b-941b-4bbc-1604-aa44d76df200",
  app: {
    browser: "https://utila.io/",
    ios: "",
    android: "",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chromewebstore.google.com/detail/utila/hcnimkhfanmcapamajjopeallkkidpic",
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: "utila.io",
  mobile: {
    native: "",
    universal: "",
  },
  desktop: {
    native: "",
    universal: "https://utila.io/",
  },
} as const;
