import { Container, Flex } from "@chakra-ui/react";
import { LandingLayout } from "components/landing-pages/layout";
import { PageId } from "page-id";
import { ThirdwebNextPage } from "utils/types";
import { MarkdownRenderer } from "../components/contract-components/published-contract/markdown-renderer";

const ToS: ThirdwebNextPage = () => {
  return (
    <LandingLayout
      seo={{
        title: "thirdweb's Terms of Service",
        description:
          "The most efficient way to build web3 apps for millions of users — with a robust infrastructure stack that scales as you grow. Learn more.",
      }}
    >
      <Container
        maxW="container.page"
        as={Flex}
        flexDir="column"
        gap={{ base: "80px", md: "120px" }}
      >
        <ToSMDX />
      </Container>
    </LandingLayout>
  );
};

const ToSMDX = () => {
  return <MarkdownRenderer markdownText={TOS_TEXT} />;
};

const TOS_TEXT = `# thirdweb Terms of Service

Thank you for using the thirdweb software development kits (“**SDK**s”), web-based development tools and downloadable software (collectively, the “**Software**”), which is developed and made available by Non-Fungible Labs, Inc. (the “**Company**”). These Terms of Service (“**Agreement**”) govern your use of the Software. You and the Company are sometimes referred to herein individually as a “**Party**” and collectively as the “**Parties**”.

**Please read this Agreement carefully, as it (among other things) provides in Section 13 that you and the Company will arbitrate certain claims instead of going to court and that you will not bring class action claims against the Company**. Please only use the Software if you agree to be legally bound by all terms and conditions herein. Your access, download or use of the Software constitutes your agreement to be bound by all terms and conditions of this Agreement. If you do not agree with any aspect of this Agreement, do not download, link your crypto wallet to, or otherwise use the Software.

As of July 2023, Non-Fungible Labs, Inc. (dba: thirdweb) has acquired Caves Inc. (dba: Paper). If you use thirdweb's services, you agree to the terms listed in thirdweb's Terms of Service in addition to the terms listed in https://withpaper.com/terms.

**Note for Children**. Use of the Software by anyone under the age of 13 is prohibited. By accessing, downloading or using the Software, you represent and warrant that are you at least 13 years of age.

The Company’s Privacy Policy, at https://thirdweb.com/privacy (the “**Privacy Policy**”), describes the collection, use and disclosure of data and information by the Company in connection with the Software. The Privacy Policy, as may be updated by the Company from time to time in accordance with its terms, is hereby incorporated into this Agreement, and you hereby agree to the collection, use and disclose practices set forth therein.

1. **Use of Software**.

1.1 License. The Software consists of a set of web-based development tools and downloadable software (including SDKS) that allows you to create blockchain-based applications and cryptographic tokens, such as non-fungible tokens, smart contracts, decentralized autonomous organizations and token marketplaces. Deployment of such applications and tokens will result in incorporation of Company’s then-current smart contract therein which may cause the Company to automatically receive a commission from transactions undertaken in respect of such applications and tokens. Subject to all terms and conditions of this Agreement, Company hereby grants you during the term of this Agreement a non-exclusive, non-transferable, limited license, with no right to grant sublicenses, to: (i) access and use the Software through a compatible web browser to the extent it is made available by the Company through a website; (ii) download, install and use the Software to the extent it is made available for download by the Company; and (iii) to the extent use of the Software results in any portion of the Software being integrated within an application or token you create through use of the Software, redistribute such portion of the Software, solely as part of such application or token, in each case of the foregoing (i) through (iii) solely in the manner made available and enabled by the Company and solely in accordance with all applicable documentation that the Company makes available from time to time. The specific capabilities, features, patches, updates and functionality of the Software are subject to change from time to time in the sole discretion of the Company and without any requirement of prior notice. In addition, you acknowledge that the Company may suspend or discontinue the Software or your ability to access it, in whole or in part, for any or no reason and without any requirement of prior notice.

1.2 Token Content. The Software may allow you to create non-fungible and fungible tokens. With respect to any text, images, videos, animations, works of authorship or other content and materials of any kind which you upload, use or submit to the Software in connection with creating tokens (“**Content**”), you represent and warrant that you either own or have all rights and licenses necessary with respect to such Content such that your use of the Content in connection with the Software will not result in any claim of infringement, misappropriation or other violation of any intellectual property rights, rights of privacy, rights of publicity or other rights of any third party. Other than as set forth in Section 1.3 below, you are solely responsible for determining the contents of any smart contract associated with any application or token you create, including with respect to the intellectual property rights that you choose to assign or license to any transferee of any token. You represent and warrant that you will not make any representations or warranties relating to the Company or the Software in connection with any applications or tokens you create through use of the Software.

1.3 Legal Compliance. You acknowledge that activities undertaken in connection your use of the Software and tokens and applications you create through use of the Software, including without limitation transacting in tokens or making available a marketplace allowing for the transaction of tokens, may be regulated by federal, state and local laws, rules and regulations, including without limitation the Securities Act of 1933 and the Securities Exchange Act of 1934, as amended. You are solely responsible for complying with, and agree to comply with, all laws, rules and regulations applicable to your use of the Software and any exploitation of any tokens and applications you create through such use. Without limiting the generality of the foregoing, you will not use the Software to create any token that may constitute a security under applicable law. You agree not to access, download or use the Software from any country in which such access, download or use is prohibited by applicable law. You hereby represent and warrant that you are not (i) located in, and will not use the Software in, a jurisdiction that is subject to United States economic sanctions, including Cuba, Iran, North Korea, Sudan, Syria or the Crimea region, (ii) a person listed on any U.S. Government blocklist (which includes the List of Specially Designated Nationals and blocked persons, the Consolidated Sanctions List administered by OFAC, and the Denied Persons List or Entity List administered by the U.S. Department of Commerce) (“**Sanctioned Person**”), or (iii) controlled or owned by a Sanctioned Person.

1.4 Assumption of Risk. You acknowledge that cryptographic and decentralized computing technologies are evolving rapidly, and that the risks associated with deploying, transacting on and otherwise using such technologies may not be fully known and are also rapidly evolving, and you hereby assume all such risks, known and unknown, whether they currently exist or develop in the future. Your further agree that the Company and its affiliates, and its and their officers, directors, employees, shareholders, contractors, attorneys, advisers and agents shall have no liability in connection with the risks of using such technologies. Without limiting the generality of the foregoing, you hereby assume all risk associated with the potential unauthorized access to, or theft or loss of, any tokens you create in connection with use of the Software.

1.5 Third Party Properties. The Software may include features or functionality provided by, or that interoperate, with software and services developed, owned, controlled and/or operated by third parties (such software and services, collectively, “**Third Party Properties**”). Third Party Properties may include, without limitation, crypto wallets and NFT marketplaces. Third Parties Properties, the availability of related featured and functionality within the Software and the interoperability of the Software with Third Party Properties may be modified, suspended or terminated at any time and without prior notice. You agree that the Company shall have no liability with respect to any of the foregoing or with respect to any errors, defects, unavailability, security breaches or other adverse events relating to any Third Party Properties. You are solely responsible for ensuring, and agree to ensure, that your use of the Software in connection with any and all Third Party Properties complies with all policies, terms and rules applicable thereto.

1.6 Support. The Company is not obligated to provide you any support or assistance related to accessing, downloading, configuring, operating or upgrading the Software, diagnosing or resolving Software-related errors or other issues, answering Software-related questions or otherwise in connection with the Software. Company may, in its sole discretion decide to provide you such support or assistance, provided that the Company may discontinue such support or assistance at any time in its sole discretion for any reason or no reason, with or without notice. Further, the Company reserves the right to charge for support in the future in its sole discretion.

2. **Commissions**. The Company’s most recent smart contract providing for commission payments to the Company (if any) will be incorporated in your applications and tokens created through use of the Software (“**Code**”) when you record such Code on a blockchain. For the avoidance of doubt, Code recorded on a blockchain at different points in time may be subject to different commission structures based on what smart contract the Company has in effect at such time. Such smart contracts will cause the Company to automatically receive a commission from all transactions undertaken in respect of such Code, by both all direct and indirect future sellers. The applicable commission structure which is determined by the Company in its sole discretion, is based on the time the Code is recorded on a blockchain and will be as displayed on [https://thirdweb.com](http://www.thirdweb.com/) at such time. You hereby consent that such commissions will be automatically deducted from the proceeds you or any subsequent seller would otherwise receive from such transactions. You agree not to attempt to delete, modify or otherwise tamper with such smart contract or otherwise take any action with the purpose or effect of adversely affecting the Company’s receipt of such commissions. You also agree to provide notice of and obtain consent to the foregoing from third parties you engage in any such transactions with and shall obligate such third parties to provide notice to and obtain consent from third parties that they engage in any such transactions with.

3. **License to Company**. You hereby grant the Company a worldwide, non-exclusive, fully paid-up, royalty-free, irrevocable, license to reproduce, modify, reformat, perform, display, transmit and otherwise use all Content submitted or provided to the Company in connection with your use of the Software in any manner that is necessary or desirable to provide the features and functionality of the Software. The aforementioned license will terminate with respect to any particular item of Content when you or the Company remove it from the Software, provided that you acknowledge that such licenses survive to the extent necessary for a copy of your Content to be retained by the Company.

4. **Representations and Warranties**. You represent, warrant and covenant to the Company, that: (a) you have the full power and authority to enter into this Agreement; (b) the execution of this Agreement and performance of its obligations under this Agreement does not violate any other agreement to which you are a party; and (c) this Agreement constitutes a legal, valid and binding obligation of such Party when executed and delivered. You also represent, warrant and covenant to Company that in connection with this Agreement or the Software, you will not attempt to: (i) violate any laws, rules or regulations or infringe or otherwise violate any third party rights; (ii) use the Software if the Company has banned or suspended you; or (iii) defraud the Company or any other person. Any potentially illegal activities undertaken in connection with the Software may be referred to any authorities deemed appropriate by the Company in its sole discretion.

5. **Ownership; Restrictions**. As between you and the Company, the Company owns all worldwide right, title and interest, including all intellectual property and other proprietary rights, in and to the Software and all usage and other data generated or collected by the Company in connection with the use thereof (the “**Company Materials**”). Except for as expressly set forth herein or as may be authorized pursuant to a separate license agreement between you and the Company, you agree not to: (i) make any unauthorized use of the Company Materials; or (ii) reverse engineer, decompile, disassemble or otherwise attempt to discover the source code, algorithm or programs underlying the Company Materials. The foregoing does not override any rights set forth pursuant to a separate open-source code license agreement agreed to in connection with any other distribution of all or part of the Software which may be made available by the Company in its sole discretion.

   The Company reserves the right to modify or discontinue the Software or any version(s) thereof at any time in its sole discretion, with or without notice.

6. **Third Party Sites**. The Software may include advertisements or other links that to third party websites or other online services that are owned and operated by third parties. If you use such links, you will leave our website. You acknowledge and agree that the Company is not responsible and shall have no liability for the content of such third party sites and services, products or services made available through them, or any use of or interaction with such sites.
7. **Prohibited Activities**. You agree not to use the Software in relation to any activities associated with or in connection to: (i) any violation of any law, rule or regulation (including without limitation those governing export control, consumer protection, unfair competition, anti-discrimination or false advertising); (ii) illegal or fraudulent goods or services, including, but not limited to, counterfeit goods, stolen goods, illegal or controlled substances, and substances that pose a risk to consumer safety, illegal online gambling / wagering, escort services, prostitution, pyramid schemes, unlicensed sale of firearms and certain weapons or any type of money laundering; or (iii) any activity that the Company deems, in its sole discretion, may be associated with a high level of risk, may create liability for the Company or may cause the Company to lose the services of any third party service providers. You may not use the Software in any manner that in the Company’s sole discretion could damage, disable, overburden, impair or interfere with any other party’s use of it. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the Software. You agree not to scrape any content from the Software or use any automated means to access, download or gather information from the Software other than such automated means which may be intentionally made available by the Company, and agree not to bypass any robot exclusion measures the Company may put into place.
8. **Additional Terms**. Use of certain features or materials on the Software, and participation in a particular promotion, event or contest through the Software, may be subject to additional terms and conditions posted on the Software. Such additional terms and conditions are hereby incorporated within this Agreement, and you agree to comply with such additional terms and conditions with respect to such use or participation.
9. **Termination**. You may terminate this Agreement at any time, without notice, for any reason or no reason, by promptly de-linking your crypto wallet from the Software, deleting all copies of the Software you may have downloaded and otherwise ceasing all use of the Software. You agree that the Company, in its sole discretion and for any or no reason, may terminate this Agreement or your use of the Software, at any time and without notice, in each case for any reason or no reason. The Company may also in its sole discretion and at any time discontinue providing the Software, or any part thereof, with or without notice and for any reason or no reason. You agree that the Company shall not be liable to you or any third-party for any such termination. Sections 1.2 through 1.6 and 2 through 14 (inclusive) will survive any termination of this Agreement.
10. **Disclaimers; No Warranties**. THE SOFTWARE AND ANY SOFTWARE CODE, DOCUMENTATION, INFORMATION OR OTHER MATERIALS MADE AVAILABLE IN CONJUNCTION WITH OR THROUGH THE SOFTWARE ARE PROVIDED “AS IS” AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, THE COMPANY AND ITS LICENSORS, SERVICE PROVIDERS AND PARTNERS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF PROPRIETARY RIGHTS. THE COMPANY AND ITS LICENSORS, SERVICE PROVIDERS AND PARTNERS DO NOT WARRANT THAT THE FEATURES AND FUNCTIONALITY OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SOFTWARE OR THE SERVERS THAT MAKE AVAILABLE THE FEATURES AND FUNCTIONALITY THEREOF ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE FOREGOING DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
11. **Indemnification**. You agree to defend, indemnify and hold harmless Company and its affiliated companies, and its and their each of their officers, directors, employees, contractors, attorneys and agents, from and against any and all claims, losses, damages, liabilities, costs and expenses, including reasonable attorney’s fees (any of the foregoing, a “**Claim**”), arising out of or relating to your: (i) use or misuse of the Software, Content, entry into or performance of any transactions relating to any tokens or applications generated in connection with the Software, breach of this Agreement or infringement, misappropriation or violation of the intellectual property or other rights of any other person or entity, provided that the foregoing does not obligate you solely to the extent the Claim arises out of the Company’s willful misconduct or gross negligence; and (ii) any appearance, testimony, deposition, production or other involvement in any way by the Company or any of its affiliated companies , or any of its or their officers, directors, employees, contractors, attorneys or agents in connection with any legal proceeding in connection with which the Software or your use thereof is being directly or indirectly relied upon, referred to or otherwise used by any party to such proceeding. The Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify the Company and you agree to cooperate with the Company’s defense of these claims. You will not make any admission of liability or agree to any settlement in connection with any Claim without Company’s prior written consent, which shall not be unreasonably withheld.
12. **Limitation of Liability and Damages**. UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE, SHALL THE COMPANY OR ITS AFFILIATES, OR ITS AND THEIR CONTRACTORS, EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, OR THIRD PARTY PARTNERS, LICENSORS OR SERVICE PROVIDERS, BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES THAT ARISE OUT OF OR RELATE TO THIS AGREEMENT OR THE SOFTWARE, INCLUDING YOUR USE THEREOF, OR ANY OTHER INTERACTIONS WITH THE COMPANY, EVEN IF THE COMPANY OR A COMPANY REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. APPLICABLE LAW MAY NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY OR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY, IN WHICH CASE THE COMPANY’S LIABILITY WILL BE LIMITED TO THE EXTENT PERMITTED BY LAW. IN NO EVENT SHALL THE TOTAL LIABILITY OF COMPANY OR ITS AFFILIATES, OR ITS AND THEIR CONTRACTORS, EMPLOYEES, OFFICERS, DIRECTORS, AGENTS, OR THIRD PARTY PARTNERS, LICENSORS OR SERVICE PROVIDERS TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR RELATING TO THIS AGREEMENT OR YOUR USE OF THE SOFTWARE EXCEED FIFTY U.S. DOLLARS.

13. **Arbitration**.

13.1 Agreement to Arbitrate. This Section 13 is referred to herein as the “**Arbitration Agreement**.” The Parties that any and all controversies, claims, or disputes between you and Company arising out of, relating to, or resulting from this Agreement or the Software, shall be subject to binding arbitration pursuant to the terms and conditions of this Arbitration Agreement, and not any court action (other than a small claims court action to the extent the claim qualifies). The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.

13.2 Class Action Waiver. THE PARTIES AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH PARTIES AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON’S OR PARTY’S CLAIMS AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY’S INDIVIDUAL CLAIM(S).

13.3 Procedures. Arbitration will be conducted by a neutral arbitrator in accordance with the American Arbitration Association’s (“**AAA**”) rules and procedures (the “**AAA Rules**”), as modified by this Arbitration Agreement. If there is any inconsistency between the AAA Rules and this Arbitration Agreement, the terms of this Arbitration Agreement will control unless the arbitrator determines that the application of the inconsistent Arbitration Agreement terms would not result in a fundamentally fair arbitration. The arbitrator must also follow the provisions of this Agreement as a court would, including without limitation, the limitation of liability provisions in Section 12. You may visit [http://www.adr.org](http://www.adr.org/) for information on the AAA and <http://www.adr.org/fileacase> for information on how to file a claim against the Company.

13.4 Venue. The arbitration shall be held in the county in which you reside if you are a US resident or at another mutually agreed location. If the value of the relief sought is $10,000 or less, you or Company may elect to have the arbitration conducted virtually or by telephone or based solely on written submissions, which election shall be binding on each Party, but subject to the arbitrator’s discretion to require an in-person hearing if the circumstances warrant. Attendance at any in-person hearing may be made virtually or by telephone by either or both Parties unless the arbitrator requires otherwise.

13.5 Governing Law. The arbitrator will decide the substance of all claims in accordance with the laws of the state of California, without regard to its conflicts of laws rules, and will honor all claims of privilege recognized by law. The arbitrator shall not be bound by rulings in prior arbitrations involving different Software users, but is bound by rulings in prior arbitrations involving you to the extent required by applicable law.

13.6 Costs of Arbitration. Payment of all filing, administration, and arbitrator fees will be governed by the AAA’s Rules. Each Party will be responsible for all other fees it incurs in connection with the arbitration, including without limitation, all attorney fees.

13.7 Confidentiality. All aspects of the arbitration proceeding, and any ruling, decision or award by the arbitrator, will be strictly confidential for the benefit of all Parties.

13.8 Severability. If a court decides that any term or provision of this Arbitration Agreement other than Section 13.2 is invalid or unenforceable, the Parties agree to replace such term or provision with a term or provision that is valid and enforceable and that comes closest to expressing the intention of the invalid or unenforceable term or provision, and this Arbitration Agreement shall be enforceable as so modified. If a court decides that any of the provisions of Section 13.2 is invalid or unenforceable, then the entirety of this Arbitration Agreement shall be null and void. The remainder of this Agreement will continue to apply.

14. **Miscellaneous**.

14.1 Changes. The Company may make modifications, deletions and/or additions to this Agreement (“**Changes**”) at any time. Changes will be effective: (i) thirty (30) days after the Company provides notice of the Changes, whether such notice is provided through the Software user interface, the Company website or otherwise; or (ii) when you opt-in or otherwise expressly agree to the Changes or a version of this Agreement incorporating the Changes, whichever comes first.

14.2 Relationship of the Parties. You and the Company are independent contractors with respect to each other. This Agreement does not constitute and shall not be construed as constituting a partnership or joint venture among the Parties hereto, or an employee-employer relationship. No Party shall have any right to obligate or bind any other Party in any manner whatsoever, and nothing herein contained shall give, or is intended to give, any rights of any kind to any third parties.

14.3 Assignment. You may not assign any of your rights or obligations under this Agreement without the prior written consent of the Company. The Company may assign its rights and obligations under this Agreement in connection with any merger (by operation of law or otherwise), consolidation, reorganization, change in control or sale of all or substantially all of its assets related to this Agreement or similar transaction. This Agreement inures to the benefit of and shall be binding on the Company’s permitted assignees, transferees and successors.

14.4 Force Majeure. You acknowledge that the Company will not be responsible for any failure or delay in its performance under this Agreement due to causes beyond its reasonable control, including, but not limited to, labor disputes, strikes, lockouts, internet or telecommunications failures, shortages of or inability to obtain labor, energy, or supplies, war, terrorism, riot, acts of God or governmental action, acts by hackers or other malicious third parties and problems with the Internet generally, and such performance shall be excused to the extent that it is prevented or delayed by reason of any of the foregoing.

14.5 Governing Law. This Agreement shall be governed by and construed in accordance with the laws of the State of California, without giving effect to any principles of conflicts of law. You agree that any action at law or in equity arising out of or relating to this Agreement or the Software that is not subject to arbitration under Section 13 shall be filed only in the state or federal courts in California (or a small claims court of competent jurisdiction) and you hereby consent and submit to the personal jurisdiction of such courts for the purposes of litigating any such action. The failure of any Party at any time to require performance of any provision of this Agreement shall in no manner affect such Party’s right at a later time to enforce the same.

14.6 Waiver. A waiver of any breach of any provision of this Agreement shall not be construed as a continuing waiver of other breaches of the same or other provisions of this Agreement. If any provision of this Agreement shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from this Agreement and shall not affect the validity and enforceability of any remaining provisions. This Agreement, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by the Company without restriction.

14.7 Headings and Wording. Unless otherwise expressly stated in this Agreement, the words "herein," "hereof," "hereto," and "hereunder" and other words of similar import refer to this Agreement as a whole and not to any particular Article, Section, Subsection, or other subdivision. The words "include" and "including" are not and should not be construed or interpreted as terms of limitation. The words "day," "month," and "year" mean, respectively, calendar day, calendar month, and calendar year. Section headings are for reference purposes only, and should not be used in the interpretation hereof. No provision of this Agreement will be construed against either Party as the drafter thereof.

14.8 Notices. Under this Agreement, you agree that all agreements, notices, disclosures, and other communications that the Company provides to you electronically satisfy any legal requirement that such communications be in writing.

14.9 Construction. This Agreement shall be fairly interpreted and construed in accordance with its terms and without strict interpretation or construction in favor of or against either Party.

14.10 Severability; Counterparts. If any provision, or portion thereof, of this Agreement is determined by a court of competent jurisdiction to be invalid, illegal or unenforceable, such determination will not impair or affect the validity, legality, or enforceability of the remaining provisions of this Agreement, and each provision, or portion thereof, is hereby declared to be separate, severable, and distinct.

14.11 Entire Agreement. This Agreement constitutes the complete, final and exclusive agreement between us with respect to the subject matter hereof, and shall not be modified except in writing, signed by both parties, or by a change to this Agreement made by the Company as set forth herein. Neither Party is relying upon any warranties, representations, assurances or inducements not expressly set forth herein.

ACTIVEUS 192650897
`;

ToS.pageId = PageId.ToS;

export default ToS;
