// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "app.mango.wallet",
  name: "Mango",
  homepage: "https://www.mangoprotocol.site/",
  image_id: "8fccdae8-cd7e-4935-5dd2-8d6dd5403500",
  app: {
    browser: "",
    ios: "",
    android: "",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chromewebstore.google.com/detail/nphpjgifdodfhachompmknpdjnhomkcc?utm_source=item-share-cb",
    firefox: "https://www.mangoprotocol.site/",
    safari: "https://www.mangoprotocol.site/",
    edge: "https://www.mangoprotocol.site/",
    opera: "https://www.mangoprotocol.site/",
  },
  rdns: "app.mango.wallet",
  mobile: {
    native: "",
    universal: "",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
