export const walletIds = {
  blocto: "blocto",
  coin98: "coin98",
  coinbase: "coinbase",
  coreWallet: "coreWallet",
  cryptoDefiWallet: "cryptoDefiWallet",
  frame: "frame",
  localWallet: "localWallet",
  magicLink: "magicLink",
  metamask: "metamask",
  paper: "paper",
  rainbow: "rainbowWallet",
  smartWallet: "smartWallet",
  tokenBoundSmartWallet: "tokenBoundSmartWallet",
  safe: "safe",
  trust: "trust",
  embeddedWallet: "embeddedWallet",
  walletConnectV1: "walletConnectV1",
  walletConnect: "walletConnect",
  phantom: "phantom",
  okx: "okx",
  oneKey: "oneKey",
  rabby: "rabby",
  // add new ids sorted alphabetically
} as const;
