// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "io.trezor",
  name: "Trezor Suite",
  homepage: "https://trezor.io/trezor-suite",
  image_id: "e205b0fd-8e50-4589-c978-c5304844a100",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/trezor-suite/id1631884497",
    android: "https://play.google.com/store/apps/details?id=io.trezor.suite",
    mac: "https://trezor.io/trezor-suite",
    windows: "https://trezor.io/trezor-suite",
    linux: "https://trezor.io/trezor-suite",
    chrome: "",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "",
  mobile: {
    native: "",
    universal: "https://connect.trezor.io/9/deeplink/wc",
  },
  desktop: {
    native: "trezorsuite://walletconnect",
    universal: "",
  },
} as const;
