// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.trustwallet.app",
  name: "Trust Wallet",
  homepage: "https://trustwallet.com/",
  image_id: "3386dde1-8b24-48c8-4b81-16979e342000",
  app: {
    browser: "",
    ios: "https://apps.apple.com/app/apple-store/id1288339409",
    android:
      "https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chrome.google.com/webstore/detail/trust-wallet/egjidjbpglichdcondbcbdnbeeppgdph",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "com.trustwallet.app",
  mobile: {
    native: "trust://",
    universal: "https://link.trustwallet.com",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
