name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        check-latest: true
        registry-url: "https://registry.npmjs.org"
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn --prefer-offline
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
