name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    # we use bun for some test suites
    - name: Setup bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      with:
        bun-version: 1.0.35
    # pnpm for our dependencies
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 9
    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: 20
        check-latest: true
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"
    - name: Install node-gyp globally
      shell: bash
      run: pnpm install -g node-gyp node-gyp-build

    - name: Install dependencies
      shell: bash
      run: pnpm install
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
