// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.magiceden.wallet&hl=en_US?utm_source=website&utm_medium=internal&utm_campaign=mobile-wallet-ga&utm_content=button",
    browser: null,
    chrome:
      "https://chromewebstore.google.com/detail/magic-eden-wallet/mkpegjkblkkefacfnmkajcjmabijhclg",
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/magic-eden-wallet/id6478631482",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://wallet.magiceden.io/",
  id: "io.magiceden.wallet",
  image_id: "62040f22-2ffd-4942-92fc-71ce68c64300",
  mobile: {
    native: "magiceden://",
    universal: null,
  },
  name: "Magic Eden",
  rdns: "io.magiceden.wallet",
} as const;
