// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=com.walletverse",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/wallet-verse-defi-buy-crypto/id6462672660",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://walletverse.io/",
  id: "io.walletverse",
  image_id: "ca91138e-0546-4cfe-071d-2181241dc600",
  mobile: {
    native: "walletverse://",
    universal: "https://walletverse.io",
  },
  name: "Walletverse",
  rdns: null,
} as const;
