// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=com.defi.wallet",
    browser: null,
    chrome:
      "https://chromewebstore.google.com/detail/cryptocom-wallet-extensio/hifafgmccdpekplomjjkcfgodnhcellj",
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/US/app/id1512048310?mt=8",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://crypto.com/onchain",
  id: "com.crypto.wallet",
  image_id: "4903acdd-6463-44b6-3cf9-f23f4c75ca00",
  mobile: {
    native: "dfw://",
    universal: "https://wallet.crypto.com",
  },
  name: "Crypto.com Onchain",
  rdns: "com.crypto.wallet",
} as const;
