// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: null,
    browser: null,
    chrome:
      "https://chromewebstore.google.com/detail/leather/ldinpeekobnhjjdofggfgjlcehhmanlj",
    edge: null,
    firefox: null,
    ios: null,
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://leather.io/",
  id: "com.wallet.reown",
  image_id: "0153454e-9313-4441-b6cf-838e3d023000",
  mobile: {
    native: null,
    universal: null,
  },
  name: "Leather",
  rdns: "com.wallet.reown",
} as const;
