// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=app.stickey",
    browser: "https://stickey.app",
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/app/id1671113083",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: "stickyapp://",
    universal: "https://stickeyapp.page.link",
  },
  homepage: "https://stickey.app",
  id: "app.stickey",
  image_id: "12aab9fb-f3d4-4248-10e0-4eda17a5de00",
  mobile: {
    native: "stickyapp://",
    universal: "https://stickeyapp.page.link",
  },
  name: "Stickey Wallet",
  rdns: null,
} as const;
