// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "io.leapwallet.CompassWallet",
  name: "Compass Wallet",
  homepage: "https://compasswallet.io/",
  image_id: "1d7dea00-96be-4ce8-ca15-d14bddbb5000",
  app: {
    browser: null,
    ios: null,
    android: null,
    mac: null,
    windows: null,
    linux: null,
    chrome:
      "https://chromewebstore.google.com/detail/compass-wallet-for-sei/anokgmphncpekkhclmingpimjmcooifb",
    firefox: null,
    safari: null,
    edge: "https://chromewebstore.google.com/detail/compass-wallet-for-sei/anokgmphncpekkhclmingpimjmcooifb",
    opera: null,
  },
  rdns: "io.leapwallet.CompassWallet",
  mobile: {
    native: null,
    universal: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
} as const;
