// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: null,
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/in/app/ancrypto-wallet/id1453657650",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://www.antiersolutions.com/",
  id: "com.antiersolutions",
  image_id: "d4382329-e288-4d7a-0ac8-3eb0facfb900",
  mobile: {
    native: "ancrypto://app",
    universal: null,
  },
  name: "Ancrypto Wallet",
  rdns: null,
} as const;
