// Pricing for each tier
export const tierPricing = {
  tier1: "Included",
  tier2: "$0.05 per SMS",
  tier3: "$0.10 per SMS",
  tier4: "$0.20 per SMS",
  tier5: "$0.40 per SMS",
} as const;

// Country names mapped to ISO codes
export const countryNames: Record<string, string> = {
  // Tier 1
  CA: "Canada",
  US: "United States",

  // Tier 2
  BH: "Bahrain",
  CN: "China",
  CR: "Costa Rica",
  GB: "United Kingdom",
  GL: "Greenland",
  KR: "Korea Republic of",
  LI: "Liechtenstein",
  NF: "Norfolk Island",
  PL: "Poland",
  PR: "Puerto Rico",
  PT: "Portugal",
  SG: "Singapore",
  TH: "Thailand",
  TR: "Turkey",
  VI: "Virgin Islands, U.S.",

  // Tier 3
  AR: "Argentina",
  AT: "Austria",
  AU: "Australia",
  BA: "Bosnia and Herzegovina",
  BN: "Brunei",
  BR: "Brazil",
  BS: "Bahamas",
  BW: "Botswana",
  CH: "Switzerland",
  CL: "Chile",
  CO: "Colombia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DK: "Denmark",
  EE: "Estonia",
  ES: "Spain",
  FI: "Finland",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GR: "Greece",
  GU: "Guam",
  HK: "Hong Kong",
  HU: "Hungary",
  IE: "Ireland",
  IN: "India",
  IS: "Iceland",
  IT: "Italy",
  JP: "Japan",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  MD: "Moldova",
  MK: "Macedonia",
  MO: "Macao",
  MT: "Malta",
  NA: "Namibia",
  NO: "Norway",
  PW: "Palau",
  RO: "Romania",
  SB: "Solomon Islands",
  SE: "Sweden",
  SK: "Slovakia",
  TW: "Taiwan",
  UY: "Uruguay",
  ZA: "South Africa",

  // Tier 4
  AD: "Andorra",
  AE: "United Arab Emirates",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AS: "American Samoa",
  AW: "Aruba",
  BB: "Barbados",
  BE: "Belgium",
  BG: "Bulgaria",
  CK: "Cook Islands",
  CM: "Cameroon",
  DJ: "Djibouti",
  DO: "Dominican Republic",
  ER: "Eritrea",
  FJ: "Fiji",
  FK: "Falkland Islands",
  GE: "Georgia",
  GF: "French Guiana",
  GI: "Gibraltar",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  HR: "Croatia",
  KI: "Kiribati",
  KN: "St Kitts and Nevis",
  LR: "Liberia",
  MC: "Monaco",
  ME: "Montenegro",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MS: "Montserrat",
  MU: "Mauritius",
  MX: "Mexico",
  NC: "New Caledonia",
  NI: "Nicaragua",
  NL: "Netherlands",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PF: "French Polynesia",
  PM: "St Pierre and Miquelon",
  PY: "Paraguay",
  RE: "Reunion/Mayotte",
  SA: "Saudi Arabia",
  SI: "Slovenia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SR: "Suriname",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  TC: "Turks and Caicos Islands",
  TO: "Tonga",
  TV: "Tuvalu",
  UA: "Ukraine",
  VE: "Venezuela",
  VN: "Vietnam",
  WF: "Wallis and Futuna",

  // Tier 5
  AF: "Afghanistan",
  AZ: "Azerbaijan",
  BD: "Bangladesh",
  BF: "Burkina Faso",
  BI: "Burundi",
  BJ: "Benin",
  BM: "Bermuda",
  BO: "Bolivia",
  BY: "Belarus",
  BZ: "Belize",
  CD: "DR Congo",
  CG: "Congo",
  CI: "Ivory Coast",
  CV: "Cape Verde",
  DM: "Dominica",
  DZ: "Algeria",
  EC: "Ecuador",
  EG: "Egypt",
  ET: "Ethiopia",
  GA: "Gabon",
  GD: "Grenada",
  GH: "Ghana",
  GT: "Guatemala",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HN: "Honduras",
  HT: "Haiti",
  IL: "Israel",
  IQ: "Iraq",
  JM: "Jamaica",
  JO: "Jordan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos PDR",
  LB: "Lebanon",
  LC: "St Lucia",
  LK: "Sri Lanka",
  LS: "Lesotho",
  LY: "Libya",
  MA: "Morocco",
  MG: "Madagascar",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MR: "Mauritania",
  MV: "Maldives",
  MW: "Malawi",
  MY: "Malaysia",
  MZ: "Mozambique",
  NE: "Niger",
  NG: "Nigeria",
  NP: "Nepal",
  PE: "Peru",
  PH: "Philippines",
  PK: "Pakistan",
  PS: "Palestinian Territory",
  QA: "Qatar",
  RS: "Serbia",
  RW: "Rwanda",
  SC: "Seychelles",
  SD: "Sudan",
  SN: "Senegal",
  SO: "Somalia",
  SS: "South Sudan",
  SY: "Syria",
  SZ: "Swaziland",
  TD: "Chad",
  TG: "Togo",
  TL: "East Timor",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TT: "Trinidad and Tobago",
  UG: "Uganda",
  VC: "St Vincent Grenadines",
  VG: "Virgin Islands, British",
  VU: "Vanuatu",
  WS: "Samoa",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
} as const;

export const countryPrefixes: Record<string, string> = {
  // Tier 1
  CA: "+1",
  US: "+1",

  // Tier 2
  BH: "+973",
  CN: "+86",
  CR: "+506",
  GB: "+44",
  GL: "+299",
  KR: "+82",
  LI: "+423",
  NF: "+672",
  PL: "+48",
  PR: "+1",
  PT: "+351",
  SG: "+65",
  TH: "+66",
  TR: "+90",
  VI: "+1",

  // Tier 3
  AR: "+54",
  AT: "+43",
  AU: "+61",
  BA: "+387",
  BN: "+673",
  BR: "+55",
  BS: "+1",
  BW: "+267",
  CH: "+41",
  CL: "+56",
  CO: "+57",
  CU: "+53",
  CY: "+357",
  CZ: "+420",
  DE: "+49",
  DK: "+45",
  EE: "+372",
  ES: "+34",
  FI: "+358",
  FM: "+691",
  FO: "+298",
  FR: "+33",
  GR: "+30",
  GU: "+1",
  HK: "+852",
  HU: "+36",
  IE: "+353",
  IN: "+91",
  IS: "+354",
  IT: "+39",
  JP: "+81",
  LT: "+370",
  LU: "+352",
  LV: "+371",
  MD: "+373",
  MK: "+389",
  MO: "+853",
  MT: "+356",
  NA: "+264",
  NO: "+47",
  PW: "+680",
  RO: "+40",
  SB: "+677",
  SE: "+46",
  SK: "+421",
  TW: "+886",
  UY: "+598",
  ZA: "+27",

  // Tier 4
  AD: "+376",
  AE: "+971",
  AG: "+1",
  AI: "+1",
  AL: "+355",
  AM: "+374",
  AO: "+244",
  AS: "+1",
  AW: "+297",
  BB: "+1",
  BE: "+32",
  BG: "+359",
  CK: "+682",
  CM: "+237",
  DJ: "+253",
  DO: "+1",
  ER: "+291",
  FJ: "+679",
  FK: "+500",
  GE: "+995",
  GF: "+594",
  GI: "+350",
  GM: "+220",
  GN: "+224",
  GP: "+590",
  GQ: "+240",
  HR: "+385",
  KI: "+686",
  KN: "+1",
  LR: "+231",
  MC: "+377",
  ME: "+382",
  MH: "+692",
  MQ: "+596",
  MS: "+1",
  MU: "+230",
  MX: "+52",
  NC: "+687",
  NI: "+505",
  NL: "+31",
  NU: "+683",
  NZ: "+64",
  OM: "+968",
  PA: "+507",
  PF: "+689",
  PM: "+508",
  PY: "+595",
  RE: "+262",
  SA: "+966",
  SI: "+386",
  SL: "+232",
  SM: "+378",
  SR: "+597",
  ST: "+239",
  SV: "+503",
  TC: "+1",
  TO: "+676",
  TV: "+688",
  UA: "+380",
  VE: "+58",
  VN: "+84",
  WF: "+681",

  // Tier 5
  AF: "+93",
  AZ: "+994",
  BD: "+880",
  BF: "+226",
  BI: "+257",
  BJ: "+229",
  BM: "+1",
  BO: "+591",
  BY: "+375",
  BZ: "+501",
  CD: "+243",
  CG: "+242",
  CI: "+225",
  CV: "+238",
  DM: "+1",
  DZ: "+213",
  EC: "+593",
  EG: "+20",
  ET: "+251",
  GA: "+241",
  GD: "+1",
  GH: "+233",
  GT: "+502",
  GW: "+245",
  GY: "+592",
  HN: "+504",
  HT: "+509",
  IL: "+972",
  IQ: "+964",
  JM: "+1",
  JO: "+962",
  KE: "+254",
  KG: "+996",
  KH: "+855",
  KW: "+965",
  KY: "+1",
  KZ: "+7",
  LA: "+856",
  LB: "+961",
  LC: "+1",
  LK: "+94",
  LS: "+266",
  LY: "+218",
  MA: "+212",
  MG: "+261",
  ML: "+223",
  MM: "+95",
  MN: "+976",
  MR: "+222",
  MV: "+960",
  MW: "+265",
  MY: "+60",
  MZ: "+258",
  NE: "+227",
  NG: "+234",
  NP: "+977",
  PE: "+51",
  PH: "+63",
  PK: "+92",
  PS: "+970",
  QA: "+974",
  RS: "+381",
  RW: "+250",
  SC: "+248",
  SD: "+249",
  SN: "+221",
  SO: "+252",
  SS: "+211",
  SY: "+963",
  SZ: "+268",
  TD: "+235",
  TG: "+228",
  TL: "+670",
  TM: "+993",
  TN: "+216",
  TT: "+1",
  UG: "+256",
  VC: "+1",
  VG: "+1",
  VU: "+678",
  WS: "+685",
  YE: "+967",
  ZM: "+260",
  ZW: "+263",
} as const;

// Helper function to convert country code to flag emoji
export const getCountryFlag = (countryCode: string) => {
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));

  return String.fromCodePoint(...codePoints);
};
