// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "net.lxxdao.wallet",
  name: "LxxDaoWallet",
  homepage: "https://www.lxxdao.net/",
  image_id: "4c179a06-3d1f-408d-4d67-93de7099e200",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/lxx-dao-crypto-wallet-app/id6764900424",
    android: "https://play.google.com/store/apps/details?id=com.lxxdao.wallet",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chromewebstore.google.com/detail/ogbdflabaoemndngioedpedkcieinfca?utm_source=item-share-cb",
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: "net.lxxdao.wallet",
  mobile: {
    native: "lxxdao://",
    universal: "https://lxxdao.net",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
