// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=co.theeasy.app",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/easy-web3-social-wallet/id1641192503",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://easy.me",
  id: "me.easy",
  image_id: "62feb41a-be1f-4b1c-e089-27f97c0e8d00",
  mobile: {
    native: "co.theeasy.app://",
    universal: "https://link.easy.me",
  },
  name: "EASY",
  rdns: null,
} as const;
