// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=app.m1nty.android",
    browser: "https://m1nty.app",
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/app/m1nty/id1643737318",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: "https://m1nty.app",
  },
  homepage: "https://m1nty.app",
  id: "app.m1nty",
  image_id: "6ccb7754-acd8-4de2-797e-a587a53d3900",
  mobile: {
    native: "m1nty://",
    universal: null,
  },
  name: "M1NTY",
  rdns: null,
} as const;
