// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.zkx.app.wallet",
  name: "ZKX Wallet",
  homepage: "https://zkxwallet.com/",
  image_id: "dd4f2b0b-d958-41a6-5352-09ddb8f4a400",
  app: {
    browser: "",
    ios: "",
    android: "",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chromewebstore.google.com/detail/zkx-web3-wallet/fibfaangghabdbndamiaceoahiajfgck",
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: "com.zkx.app.wallet",
  mobile: {
    native: "",
    universal: "",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
