// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "io.rabby",
  name: "Rabby",
  homepage: "https://rabby.io/",
  image_id: "255e6ba2-8dfd-43ad-e88e-57cbb98f6800",
  app: {
    browser:
      "https://chrome.google.com/webstore/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch",
    ios: "https://apps.apple.com/us/app/rabby-wallet-crypto-evm/id6474381673",
    android:
      "https://play.google.com/store/apps/details?id=com.debank.rabbymobile",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chrome.google.com/webstore/detail/rabby-wallet/acmacodkjbdgmoleebolmdjonilkdbch",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "io.rabby",
  mobile: {
    native: "rabby://",
    universal: "",
  },
  desktop: {
    native: "",
    universal:
      "https://chrome.google.com/webstore/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch",
  },
} as const;
