// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=com.lif3.wallet",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/app/lif3/id6444389674",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://lif3.com/",
  id: "com.lif3",
  image_id: "1a89c0ec-9059-4515-afb6-8204d49f0900",
  mobile: {
    native: "lif3wallet://walletview",
    universal: null,
  },
  name: "Lif3 Wallet",
  rdns: null,
} as const;
