// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.okex.wallet",
  name: "OKX Wallet",
  homepage: "https://www.okx.com/download",
  image_id: "c55df831-3c52-49fc-d1d1-97a926dc0c00",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/okx-wallet-portal-to-web3/id6743309484",
    android: "https://play.google.com/store/apps/details?id=com.okx.wallet",
    mac: "",
    windows: "",
    linux: "",
    chrome:
      "https://chrome.google.com/webstore/detail/okx-wallet/mcohilncbfahbmgdjkbpemcciiolgcge",
    firefox: "",
    safari: "",
    edge: "",
    opera: "",
  },
  rdns: "com.okex.wallet",
  mobile: {
    native: "okxwallet://main",
    universal: "https://web3.okx.com/download",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
