// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.aktionariat.app",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/ch/app/aktionariat/id1518326813",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://aktionariat.com/",
  id: "com.aktionariat",
  image_id: "6d18e8ea-b536-4038-c5bf-94a499d5a400",
  mobile: {
    native: "aktionariat://",
    universal: "https://app.aktionariat.com",
  },
  name: "Aktionariat",
  rdns: null,
} as const;
