// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.ukey",
  name: "UKey Wallet",
  homepage: "https://ukey.com",
  image_id: "c35479b7-c228-4859-1f9b-406493f00000",
  app: {
    browser: "",
    ios: "https://apps.apple.com/fr/app/ukey-crypto-bitcoin-wallet/id6758265264",
    android: "https://play.google.com/store/apps/details?id=app.ukey.io",
    mac: "",
    windows: "",
    linux: "",
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "ukey-wallet://",
    universal: "https://app.ukey.io/wc/connect",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
