// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  id: "com.it.onewallet",
  name: "onewallet",
  homepage: "https://onewallet.it.com/",
  image_id: "49a8ef2d-fa6f-43d2-09d8-c63b3704d400",
  app: {
    browser: "",
    ios: "https://apps.apple.com/us/app/one-wallet-stablecoin/id6749446601?l=zh-Hans-CN",
    android: "",
    mac: "",
    windows: "",
    linux: "",
    chrome: null,
    firefox: null,
    safari: null,
    edge: null,
    opera: null,
  },
  rdns: null,
  mobile: {
    native: "onewallet://wallet",
    universal: "https://onewallet.it.com/ws",
  },
  desktop: {
    native: "",
    universal: "",
  },
} as const;
