// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=co.bacoor.keyring",
    browser: "https://keyring.app/",
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/keyring-pro-wallet-management/id1546824976",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: "https://keyring.app/",
  },
  homepage: "https://keyring.app/",
  id: "app.keyring",
  image_id: "dda0f0fb-34e8-4a57-dcea-b008e7d1ff00",
  mobile: {
    native: "keyring://",
    universal: "https://keyring.app/",
  },
  name: "KEYRING PRO",
  rdns: null,
} as const;
