// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: null,
    browser: null,
    chrome: "https://brave.com/wallet/",
    edge: null,
    firefox: null,
    ios: null,
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://brave.com/wallet/",
  id: "com.brave.wallet",
  image_id: "8cecad66-73e3-46ee-f45f-01503c032f00",
  mobile: {
    native: null,
    universal: null,
  },
  name: "Brave Wallet",
  rdns: "com.brave.wallet",
} as const;
