// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.dok.wallet&pli=1",
    browser: "https://www.dokwallet.app",
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/il/app/dokwallet-crypto-wallet/id1533065700",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://www.dokwallet.com",
  id: "com.dokwallet",
  image_id: "5707f35e-17a1-42b3-35c5-664f7655cd00",
  mobile: {
    native: "dokwallet://",
    universal: "https://www.dokwallet.app",
  },
  name: "Dokwallet",
  rdns: null,
} as const;
