/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IERC1155Supply,
  IERC1155SupplyInterface,
} from "../IERC1155Supply";
import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC1155Supply__factory {
  static readonly abi = _abi;
  static createInterface(): IERC1155SupplyInterface {
    return new utils.Interface(_abi) as IERC1155SupplyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC1155Supply {
    return new Contract(address, _abi, signerOrProvider) as IERC1155Supply;
  }
}
