import {
  Arbitrum,
  ArbitrumSepolia,
  Avalanche,
  AvalancheFuji,
  Base,
  BaseSepoliaTestnet,
  Binance,
  BinanceTestnet,
  Ethereum,
  Localhost,
  OpSepoliaTestnet,
  Optimism,
  Polygon,
  PolygonAmoyTestnet,
  Sepolia,
} from "@thirdweb-dev/chains";

export const popularChains = [
  Ethereum,
  Sepolia,
  Polygon,
  PolygonAmoyTestnet,
  Base,
  BaseSepoliaTestnet,
  Arbitrum,
  ArbitrumSepolia,
  Optimism,
  OpSepoliaTestnet,
  Binance,
  BinanceTestnet,
  Avalanche,
  AvalancheFuji,
  Localhost,
];
