// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android:
      "https://play.google.com/store/apps/details?id=com.kraken.superwallet",
    browser: null,
    chrome: null,
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/us/app/kraken-wallet/id1626327149",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://www.kraken.com/wallet",
  id: "com.kraken",
  image_id: "3f4e6025-d008-4edc-1fbd-19f54294a900",
  mobile: {
    native: "krakenwallet://",
    universal: null,
  },
  name: "Kraken Wallet ",
  rdns: null,
} as const;
