// This file is auto-generated by the `scripts/wallets/generate.ts` script.
// Do not modify this file manually.

export const wallet = {
  app: {
    android: "https://play.google.com/store/apps/details?id=com.wigwamapp",
    browser: null,
    chrome:
      "https://chromewebstore.google.com/detail/wigwam-%E2%80%94-web3-wallet/lccbohhgfkdikahanoclbdmaolidjdfl",
    edge: null,
    firefox: null,
    ios: "https://apps.apple.com/app/id6630381643",
    linux: null,
    mac: null,
    opera: null,
    safari: null,
    windows: null,
  },
  desktop: {
    native: null,
    universal: null,
  },
  homepage: "https://wigwam.app",
  id: "com.wigwam.wallet",
  image_id: "6200b005-f202-41d5-7bd9-966c970f6700",
  mobile: {
    native: "wigwam://",
    universal: "https://wigwam.app/",
  },
  name: "Wigwam",
  rdns: "com.wigwam.wallet",
} as const;
