name: Benchmark

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # To use Remote Caching, uncomment the next lines and follow the steps below.
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}

jobs:
  benchmark:
    timeout-minutes: 15
    name: "Benchmark"
    runs-on: ubuntu-latest-16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: "pnpm bench"
