name: E2E Tests (legacy)

on:
  push:
    branches: ["main"]
    paths: ["legacy_packages/**", "legacy_e2e/**"]
  pull_request:
    types: [opened, synchronize]
    paths: ["legacy_packages/**", "legacy_e2e/**"]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # To use Remote Caching, uncomment the next lines and follow the steps below.
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  e2e:
    timeout-minutes: 15
    name: E2E Tests
    runs-on: ubuntu-latest-16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: pnpm e2e
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          CLI_E2E_API_KEY: ${{ secrets.CLI_E2E_API_KEY }}
