# On the Version Packages branch
# Generate and Commit snippets JSON files

name: Commit Snippets JSON files

on:
  push:
    branches:
      - changeset-release/main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.21

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build

      - name: generate-docs
        run: pnpm generate-docs

      - name: generate-snippets
        run: pnpm generate-snippets

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Commit Release Artifacts [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
