# On the Version Packages branch created by github-actions[bot]
# Run `pnpm build`, `pnpm generate-docs` and `pnpm generate-snippets` to generate JSON files in the snippets folder
# Commit the generated JSON files to the Version Packages branch

name: Commit code snippets

on:
  push:
    branches:
      - changeset-release/main

jobs:
  typedoc:
    if: github.actor == 'github-actions[bot]'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: build
        run: pnpm build

      - name: generate-docs
        run: pnpm generate-docs

      - name: generate-snippets
        run: pnpm generate-snippets

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "snippets: update JSON files [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
