name: Unit Tests

on:
  push:
    branches: ["main"]
    paths: ["packages/**"]
  pull_request:
    types: [opened, synchronize]
    paths: ["packages/**"]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

  # To use Remote Caching, uncomment the next lines and follow the steps below.
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TW_SECRET_KEY: ${{ secrets.TW_SECRET_KEY }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test:
    timeout-minutes: 15
    name: Unit Tests
    runs-on: ubuntu-latest-16
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1

      - run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./packages
